Repository openedx/edx-proctoring, pull requests merged in 2020-07, with the labels that each got.

#692 [BD-18] Remove nose dependency
  .gitignore
  edx_proctoring/apps.py
  edx_proctoring/backends/rest.py
  edx_proctoring/backends/tests/test_backend.py
  edx_proctoring/management/commands/set_attempt_status.py
  edx_proctoring/services.py
  edx_proctoring/signals.py
  edx_proctoring/tests/__init__.py
  requirements/base.txt
  requirements/dev.txt
  requirements/doc.txt
  requirements/quality.txt
  requirements/test.in
  requirements/test.txt
Labels: blended, needs triage

#697 standarize make test target
  Makefile
Labels: community manager review, open-source-contribution

#699 Fix authoring doc link in README
  README.rst
Labels: awaiting prioritization, open-source-contribution
